### ISSUE TITLE
Cannot be used at the same time as SWCAN library

### ISSUE THREAD

**Issue by rfrowe** [macchina/M2_SD_HSMCI#11]
This library is incompatible with [macchina/Single-Wire-CAN-mcp2515](https://github.com/macchina/Single-Wire-CAN-mcp2515). This is due to an error in this library which incorrectly uses pin 64, which is not marked as an SD pin but insteaed a SWCAN pin on the [M2 pin mappings](https://docs.macchina.cc/m2-docs/detailed-reference/pin-mapping), as the card detection pin, causing interoperability issues with SWCAN due to its use of that pin as `SWC_M0`

**Comment by tjb8907** [comment]
This just saved me some headaches! Couldn't figure out why SD would work with the example but not my program running SWCAN! Thanks!

**Comment by rocketjosh** [comment]
Thanks @rfrowe, good find, I appreciate it. I just merged both of your pull requests.

**Comment by rfrowe** [comment]
@tjb8907 Glad my headache could save you from yours. This took a while to track down. It's a tricky one because, at least for me, the program would work fine for about 10 seconds then halt.

@rocketjosh Thank you for merging! Now I can take some manual patches out of my readme 🤣

**Comment by rfrowe** [comment]
Fixed by #12
